name: CI/CD Pipeline for BankSimulation Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build and Test in Docker
        run: |
          docker build -t mohamum2/bank-simulation:latest .
          docker run --rm mohamum2/bank-simulation:latest

  dockerize:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-actions@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t mohamum2/bank-simulation:latest .
      - name: Push Docker Image
        run: |
          docker push mohamum2/bank-simulation:latest
