name: CI/CD Pipeline for BankSimulation Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t mohamum2/demos:${{ github.sha }} .

      - name: Run Docker Image
        run: |
          docker run --rm -d --name demo-container --dns 8.8.8.8 mohamum2/demos:${{ github.sha }} bash -c "
            mkdir -p /app/build;
            cd /app/build &&
            cmake .. && make &&
            ctest -V > /app/test_results.log
          "
          # Sleep for a bit to ensure the test run completes
          sleep 10  # Adjust this as needed

      - name: Check if the Container is Running
        run: |
          docker ps -a | grep demo-container || echo "demo-container is not running"

      - name: Inspect Docker Logs for Errors
        run: |
          docker logs demo-container || echo "No logs available for demo-container"

      - name: Copy Test Results from Docker Container
        run: |
          docker cp demo-container:/app/test_results.log /tmp/test_results.log || echo "Failed to copy test results"

      - name: Verify Test Results File
        run: |
          ls -l /tmp/test_results.log || echo "Test results file not found"
          cat /tmp/test_results.log || echo "Failed to read test results"

      - name: Save Docker Image to .tar
        run: |
          docker save mohamum2/demos:${{ github.sha }} -o /tmp/demos_${{ github.sha }}.tar
          ls -l /tmp/demos_${{ github.sha }}.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: demos-image
          path: /tmp/demos_${{ github.sha }}.tar

      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /tmp/test_results.log

  push-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: demos-image
          path: /tmp

      - name: Load Docker Image
        run: |
          docker load -i /tmp/demos_${{ github.sha }}.tar

      - name: Push Docker Image
        run: |
          docker images
          docker push mohamum2/demos:${{ github.sha }}
