name: CI/CD Pipeline for BankSimulation Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t mohamum2/demos:${{ github.sha }} .

      - name: Verify Docker Image
        run: |
          docker images
          docker run --rm mohamum2/demos:${{ github.sha }} bash -c "echo 'Test start' > /app/test_results.log; cd /app/build && cmake .. && make && ctest >> /app/test_results.log"
      - name: Save Docker Image to .tar
        run: |
          docker save mohamum2/demos:${{ github.sha }} -o /tmp/demos_${{ github.sha }}.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: demos-image
          path: /tmp/demos_${{ github.sha }}.tar

      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /app/test_results.log

  push-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: demos-image
          path: /tmp

      - name: Load Docker Image
        run: |
          docker load -i /tmp/demos_${{ github.sha }}.tar

      - name: Push Docker Image
        run: |
          docker images
          docker push mohamum2/demos:${{ github.sha }}
