name: CI/CD Pipeline for BankSimulation Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t mohamum2/demos:${{ github.sha }} .

      - name: Run Tests inside Docker
        run: |
          docker run --rm mohamum2/demos:${{ github.sha }} ctest --output-on-failure

      - name: Save Docker Image
        run: |
          docker save mohamum2/demos:${{ github.sha }} -o /tmp/demos.tar

      - uses: actions/upload-artifact@v2
        with:
          name: demos-image
          path: /tmp/demos.tar

  push-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Docker Image
        uses: actions/download-artifact@v2
        with:
          name: demos-image

      - name: Load Docker Image
        run: |
          docker load -i demos.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push mohamum2/demos:${{ github.sha }}
